import { useState, useRef, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import { Badge } from "./ui/index.jsx";

const inputStyle = {
  width: "100%",
  fontFamily: "var(--font-sans)",
  fontSize: "13px",
  color: "var(--color-text-primary)",
  background: "var(--color-background-secondary)",
  border: "0.5px solid var(--color-border-secondary)",
  borderRadius: "var(--border-radius-md)",
  padding: "12px 14px",
  outline: "none",
  resize: "none",
  transition: "border-color 0.2s ease"
};

const buttonStyle = {
  padding: "8px 16px",
  fontSize: "13px",
  fontWeight: 500,
  background: "var(--color-background-info)",
  border: "0.5px solid var(--color-border-info)",
  borderRadius: "var(--border-radius-md)",
  cursor: "pointer",
  color: "var(--color-text-info)",
  display: "flex",
  alignItems: "center",
  gap: "6px",
  justifyContent: "center",
  boxShadow: "var(--glow-info)",
  transition: "all 0.2s ease"
};

const secondaryButtonStyle = {
  ...buttonStyle,
  background: "var(--color-background-secondary)",
  border: "0.5px solid var(--color-border-tertiary)",
  color: "var(--color-text-primary)",
  boxShadow: "none"
};

export default function SynthesisChat() {
  const [apiKey, setApiKey] = useState(() => localStorage.getItem("ninety_gemini_key") || "");
  const [isAuth, setIsAuth] = useState(!!localStorage.getItem("ninety_gemini_key"));
  const [showKey, setShowKey] = useState(false);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const chatEndRef = useRef(null);
  const textareaRef = useRef(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading]);

  const handleAuth = (e) => {
    e.preventDefault();
    if (apiKey.trim().length > 10) {
      localStorage.setItem("ninety_gemini_key", apiKey.trim());
      setIsAuth(true);
    }
  };

  const handleClearAuth = () => {
    localStorage.removeItem("ninety_gemini_key");
    setApiKey("");
    setIsAuth(false);
    setMessages([]);
  };

  const clearChat = () => {
    setMessages([]);
  };

  const handleInput = (e) => {
    setInput(e.target.value);
    // Auto-resize textarea
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 150) + "px";
    }
  };

  const sendMessage = async () => {
    if (!input.trim() || loading) return;
    
    const userText = input.trim();
    setInput("");
    
    // Reset textarea height
    if (textareaRef.current) {
      textareaRef.current.style.height = "50px";
    }
    
    const newMessages = [...messages, { role: "user", text: userText }];
    setMessages(newMessages);
    setLoading(true);

    try {
      const systemInstruction = "You are an elite YouTube scriptwriter and strategist for a premium media brand. When provided a topic, generate:\n1. Three high-CTR title ideas.\n2. Two highly clickable thumbnail visual concepts.\n3. A fast-paced, highly engaging script optimized for retention.\nAlways include clear visual cues in [brackets], an instant pattern-interrupt hook in the first 5 seconds, a tight narrative structure, and a strong call to action. Do not use generic filler phrasing. Maintain an authoritative, premium, and energetic tone.";
      
      // Filter out any potential system or non-user/model messages, and ensure it alternates correctly
      // Gemini requires the conversation to start with a 'user' role.
      const contents = newMessages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));

      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: systemInstruction }] },
          contents: contents
        })
      });

      const data = await res.json();
      
      if (data.error) {
        throw new Error(data.error.message);
      }

      if (!data.candidates || data.candidates.length === 0) {
        throw new Error("No response generated by the model.");
      }

      const modelReply = data.candidates[0].content.parts[0].text;
      setMessages(prev => [...prev, { role: "model", text: modelReply }]);
    } catch (err) {
      setMessages(prev => [...prev, { role: "model", text: `**Error:** Synthesis failed. ${err.message}` }]);
    } finally {
      setLoading(false);
    }
  };

  if (!isAuth) {
    return (
      <div style={{ marginTop: "2rem", display: "flex", justifyContent: "center", alignItems: "center", height: "calc(100vh - 120px)" }}>
        <div style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "3rem", textAlign: "center", maxWidth: "480px", width: "100%", boxShadow: "0 10px 40px rgba(0,0,0,0.5)" }}>
          <div style={{ width: "64px", height: "64px", background: "var(--color-background-secondary)", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 1.5rem", border: "1px solid var(--color-border-secondary)" }}>
            <i className="ti ti-lock-square-rounded" style={{ fontSize: 32, color: "var(--color-text-secondary)" }}></i>
          </div>
          <h2 style={{ fontSize: 20, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: "12px" }}>Synthesis Engine Access</h2>
          <p style={{ fontSize: 13, color: "var(--color-text-secondary)", marginBottom: "2.5rem", lineHeight: 1.6 }}>
            Please authenticate with your Google AI Studio API key to activate the premium scripting engine. Keys are securely encrypted in local storage.
          </p>
          <form onSubmit={handleAuth} style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            <div style={{ position: "relative" }}>
              <input 
                type={showKey ? "text" : "password"} 
                style={{ ...inputStyle, paddingRight: "40px" }} 
                placeholder="Enter Gemini API Key..." 
                value={apiKey} 
                onChange={e => setApiKey(e.target.value)} 
              />
              <button 
                type="button"
                onClick={() => setShowKey(!showKey)}
                style={{ position: "absolute", right: "12px", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", color: "var(--color-text-tertiary)", cursor: "pointer" }}
              >
                <i className={`ti ${showKey ? 'ti-eye-off' : 'ti-eye'}`}></i>
              </button>
            </div>
            <button type="submit" style={{...buttonStyle, width: "100%", padding: "12px", fontSize: "14px"}}>Initialize Engine</button>
          </form>
          <p style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginTop: "2rem" }}>
            <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer" style={{ color: "var(--color-text-info)", textDecoration: "none", display: "flex", alignItems: "center", justifyContent: "center", gap: "4px" }}>
              Obtain API Key <i className="ti ti-external-link"></i>
            </a>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "calc(100vh - 120px)", marginTop: "1.5rem" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.25rem" }}>
        <h2 style={{ fontSize: 18, fontWeight: 500, margin: 0, color: "var(--color-text-primary)", display: "flex", alignItems: "center", gap: "8px" }}>
          <i className="ti ti-cpu" style={{ color: "var(--color-text-info)" }}></i> Synthesis Engine
        </h2>
        <div style={{ display: "flex", gap: "12px", alignItems: "center" }}>
          {messages.length > 0 && (
            <button onClick={clearChat} style={secondaryButtonStyle}>
              <i className="ti ti-trash" /> Clear
            </button>
          )}
          <Badge color="success">Secure Connection Active</Badge>
          <button onClick={handleClearAuth} style={{ ...secondaryButtonStyle, border: "none", background: "transparent", padding: "8px" }}>
            <i className="ti ti-logout" />
          </button>
        </div>
      </div>

      <div style={{ 
        flex: 1, 
        background: "var(--color-background-primary)", 
        border: "0.5px solid var(--color-border-tertiary)", 
        borderRadius: "var(--border-radius-lg)", 
        overflowY: "auto", 
        padding: "1.5rem",
        display: "flex",
        flexDirection: "column",
        gap: "1.5rem",
        marginBottom: "1.25rem",
        boxShadow: "inset 0 2px 10px rgba(0,0,0,0.2)"
      }}>
        {messages.length === 0 ? (
          <div style={{ height: "100%", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "var(--color-text-tertiary)", opacity: 0.7 }}>
            <i className="ti ti-brain" style={{ fontSize: 48, marginBottom: "1rem", color: "var(--color-text-secondary)" }}></i>
            <h3 style={{ fontSize: 16, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: "8px" }}>Engine Ready for Synthesis</h3>
            <p style={{ fontSize: 13, maxWidth: "300px", textAlign: "center", lineHeight: 1.6 }}>
              Enter a topic below to automatically generate high-CTR titles, clickable thumbnail concepts, and a highly-retentive script.
            </p>
          </div>
        ) : (
          messages.map((m, i) => (
            <div key={i} style={{ 
              display: "flex", 
              flexDirection: "column", 
              alignItems: m.role === "user" ? "flex-end" : "flex-start" 
            }}>
              <div style={{ 
                fontSize: 11, 
                color: "var(--color-text-tertiary)", 
                marginBottom: 6,
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                display: "flex",
                alignItems: "center",
                gap: 6
              }}>
                {m.role === "user" ? <><i className="ti ti-user" /> Executive</> : <><i className="ti ti-brain" style={{color: "var(--color-text-info)"}} /> Synthesis Engine</>}
              </div>
              <div style={{ 
                background: m.role === "user" ? "var(--color-background-tertiary)" : "transparent",
                border: m.role === "user" ? "0.5px solid var(--color-border-secondary)" : "none",
                padding: m.role === "user" ? "12px 16px" : "0 4px",
                borderRadius: "var(--border-radius-md)",
                maxWidth: m.role === "user" ? "80%" : "100%",
                color: m.role === "user" ? "var(--color-text-primary)" : "var(--color-text-secondary)",
                fontSize: "13.5px",
                lineHeight: 1.6,
                fontFamily: "var(--font-sans)"
              }}>
                {m.role === "user" ? (
                  <div style={{ whiteSpace: "pre-wrap" }}>{m.text}</div>
                ) : (
                  <div className="markdown-body" style={{ color: "var(--color-text-primary)" }}>
                    <ReactMarkdown>{m.text}</ReactMarkdown>
                  </div>
                )}
              </div>
            </div>
          ))
        )}
        
        {loading && (
          <div style={{ display: "flex", alignItems: "flex-start", flexDirection: "column" }}>
            <div style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.05em", display: "flex", alignItems: "center", gap: 6 }}>
              <i className="ti ti-brain" style={{color: "var(--color-text-info)"}} /> Synthesis Engine
            </div>
            <div style={{ color: "var(--color-text-info)", fontSize: 13, display: "flex", alignItems: "center", gap: 8, padding: "0 4px" }}>
              <i className="ti ti-loader" style={{ animation: "spin 2s linear infinite" }} /> Processing intelligence...
            </div>
          </div>
        )}
        <div ref={chatEndRef} />
      </div>

      <div style={{ display: "flex", gap: "10px", alignItems: "flex-end" }}>
        <textarea 
          ref={textareaRef}
          style={{ ...inputStyle, minHeight: "50px", maxHeight: "150px", padding: "14px 16px", borderRadius: "var(--border-radius-lg)" }} 
          placeholder="Deploy a topic for synthesis..."
          value={input}
          onChange={handleInput}
          onKeyDown={e => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              sendMessage();
            }
          }}
        />
        <button 
          style={{ ...buttonStyle, height: "50px", padding: "0 24px", borderRadius: "var(--border-radius-lg)", opacity: loading ? 0.7 : 1, cursor: loading ? "not-allowed" : "pointer" }} 
          onClick={sendMessage}
          disabled={loading || !input.trim()}
        >
          <i className="ti ti-send" style={{ fontSize: 18 }} />
        </button>
      </div>
      
      <style>{`
        @keyframes spin { 100% { transform: rotate(360deg); } }
        .markdown-body h1, .markdown-body h2, .markdown-body h3 {
          color: var(--color-text-primary);
          margin-top: 1.5em;
          margin-bottom: 0.75em;
          font-weight: 600;
          letter-spacing: -0.01em;
        }
        .markdown-body h3 { font-size: 1.1em; color: var(--color-text-info); }
        .markdown-body p { margin-bottom: 1.25em; }
        .markdown-body ul, .markdown-body ol { margin-bottom: 1.25em; padding-left: 2em; }
        .markdown-body li { margin-bottom: 0.4em; }
        .markdown-body strong { color: var(--color-text-primary); font-weight: 600; }
        .markdown-body em { color: var(--color-text-secondary); }
        .markdown-body code {
          background: var(--color-background-tertiary);
          padding: 0.2em 0.4em;
          border-radius: 4px;
          font-family: var(--font-mono);
          font-size: 0.9em;
          border: 1px solid var(--color-border-secondary);
        }
        .markdown-body blockquote {
          border-left: 3px solid var(--color-border-info);
          padding-left: 1em;
          margin-left: 0;
          color: var(--color-text-secondary);
          background: var(--color-background-tertiary);
          padding: 0.5em 1em;
          border-radius: 0 4px 4px 0;
        }
        textarea:focus {
          border-color: var(--color-border-info) !important;
        }
      `}</style>
    </div>
  );
}
